"""added permissions table

Revision ID: 00c569987c68
Revises: 32ae1b1a68ed
Create Date: 2024-03-09 20:11:43.419508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00c569987c68'
down_revision: Union[str, None] = '32ae1b1a68ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'permissions',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'permissions',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               nullable=True)
    # ### end Alembic commands ###
