"""add job, email

Revision ID: 2051c99a904d
Revises: 5948915c5b34
Create Date: 2024-03-03 20:54:09.867142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2051c99a904d'
down_revision: Union[str, None] = '5948915c5b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('job', sa.String(length=50), nullable=False))
    op.add_column('Users', sa.Column('email', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'Users', ['job'])
    op.create_unique_constraint(None, 'Users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_column('Users', 'email')
    op.drop_column('Users', 'job')
    # ### end Alembic commands ###
