"""added permissions column

Revision ID: 32ae1b1a68ed
Revises: 9013c25717d7
Create Date: 2024-03-09 19:42:52.294497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ae1b1a68ed'
down_revision: Union[str, None] = '9013c25717d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('permissions', sa.ARRAY(sa.String(length=50)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'permissions')
    # ### end Alembic commands ###
