"""initial migration

Revision ID: 9013c25717d7
Revises: 
Create Date: 2024-03-08 15:25:54.001102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9013c25717d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password', sa.String(length=50), nullable=True))
    op.alter_column('Users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('Users', 'job')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('job', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('Users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('Users', 'password')
    # ### end Alembic commands ###
