"""modify job, email

Revision ID: cbc97866e1bf
Revises: 2051c99a904d
Create Date: 2024-03-03 20:55:13.150218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc97866e1bf'
down_revision: Union[str, None] = '2051c99a904d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'job',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('Users_job_key', 'Users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Users_job_key', 'Users', ['job'])
    op.alter_column('Users', 'job',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
